# Generated by Django 4.1.7 on 2023-03-24 09:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeatsInWeek', django_mysql.models.ListCharField(models.CharField(max_length=3), max_length=27, size=7)),
                ('wordsBeingStudied', models.SmallIntegerField()),
                ('wordsListsNames', models.TextField()),
                ('updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WordsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.SmallIntegerField()),
                ('word', models.CharField(max_length=32)),
                ('article', models.CharField(max_length=3)),
                ('example', models.TextField()),
                ('translate', models.CharField(max_length=32)),
                ('transcription', models.CharField(max_length=45)),
                ('lastRepeat', models.DateTimeField()),
                ('nextRepeat', models.DateTimeField()),
                ('repeats', models.SmallIntegerField()),
            ],
        ),
    ]
