# Generated by Django 4.1.7 on 2023-03-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.SmallIntegerField()),
                ('word', models.CharField(max_length=32)),
                ('article', models.CharField(max_length=3)),
                ('example', models.TextField()),
                ('translate', models.CharField(max_length=32)),
                ('transcription', models.CharField(max_length=45)),
                ('lastRepeat', models.DateTimeField()),
                ('nextRepeat', models.DateTimeField()),
                ('repeats', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='WordsStats',
            new_name='MainWord',
        ),
        migrations.RenameModel(
            old_name='UserStats',
            new_name='UserStat',
        ),
    ]
