# Generated by Django 4.1.7 on 2023-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wordsstat_rename_wordsstats_mainword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainword',
            name='table_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
