# Generated by Django 4.1.7 on 2023-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_mainword_lastrepeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsstat',
            name='user_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
