# Generated by Django 4.1.7 on 2023-03-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wordsstat_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='user_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
