# Generated by Django 4.1.7 on 2023-03-24 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userstat_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 16, 16, 44, 190718)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='wordsBeingStudied',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='wordsListsNames',
            field=models.TextField(default="'Основные слова':'0'"),
        ),
    ]
