# Generated by Django 4.1.7 on 2023-03-24 13:17

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userstat_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='repeatsInWeek',
            field=django_mysql.models.ListCharField(models.CharField(max_length=3), default=[0, 0, 0, 0, 0, 0, 0], max_length=27, size=7),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 16, 17, 58, 417656)),
        ),
    ]
