# Generated by Django 4.1.7 on 2023-03-24 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userstat_repeatsinweek_alter_userstat_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 16, 19, 28, 438215)),
        ),
        migrations.AlterField(
            model_name='wordsstat',
            name='lastRepeat',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 16, 19, 28, 439214)),
        ),
        migrations.AlterField(
            model_name='wordsstat',
            name='nextRepeat',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 16, 19, 28, 439214)),
        ),
        migrations.AlterField(
            model_name='wordsstat',
            name='repeats',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordsstat',
            name='table_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
