# Generated by Django 4.1.7 on 2023-03-25 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_userstat_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 14, 41, 35, 695285)),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='wordsListsNames',
            field=models.TextField(default='Основные слова'),
        ),
        migrations.AlterField(
            model_name='wordsstat',
            name='lastRepeat',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 14, 41, 35, 696284)),
        ),
        migrations.AlterField(
            model_name='wordsstat',
            name='nextRepeat',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 14, 41, 35, 696284)),
        ),
    ]
